// client/pages/_app.js

// import {UserProvider} from '../context';
 import Navbar from '@/components/Navbar';
import React from 'react';
import { Route, Router, Routes } from 'react-router-dom';
import HomePage from './HomePage';
import PatientsPage from './PatientsPage';
import AddPatientPage from './AddPatientPage';
// import "bootstrap/dist/css/bootstrap.min.css";
// import Navbar from'../components/Nav';
// import Head from 'next/head';
// import {ToastContainer} from 'react-toastify';
// import 'react-toastify/dist/ReactToastify.css';
// import { StyleProvider } from '@ant-design/cssinjs';
// import '../public/globalcss/styles.css';

interface MyAppProps {
  // Define your component props here
  pageProps: any;
  Component: any;
}

   function MyApp({ Component, pageProps }: MyAppProps) {
    return (
      <Router location={window.location} navigator={window.history as any}>
        <Navbar />
        <h1>Welcome to Next.js!</h1>
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/patients" element={<PatientsPage />} />
          <Route path="/add-patient" element={<AddPatientPage />} />
        </Routes>
      </Router>

      //     <UserProvider>
      //     <StyleProvider hashPriority='high'>
      //     <Head>
      //       <title>My socialApp</title>
      //       <meta name="description" content="Generated by create next app" />
      //       <link rel="icon" href="/images/favicon.png"  />
      //     </Head>
      //       <Navbar />
      //       <ToastContainer position='top-center'/>
      //       <Component {...pageProps} />
      //     </StyleProvider>
      //     </UserProvider>
    );

} export default MyApp;